### ISSUE TITLE
GHA config

### ISSUE THREAD

**Issue by grahamc** [DeterminateSystems/magic-nix-cache#2]
Tracking how I'm using this in GHA.

This config seems to work ok, and handles when GHA gets mad:

```
      - name: "Run the Nix Action Cache"
        run: ./nix-action-cache --cache-version "$(sha256sum ./nix-action-cache  | cut -d' ' -f1)" --upstream https://cache.nixos.org &

      - uses: DeterminateSystems/nix-installer-action@v2
        with:
          extra-conf: |
            extra-substituters = http://127.0.0.1:3000/?trusted=1&compression=zstd&parallel-compression=true
            fallback = true

```
