### ISSUE TITLE
Causing severe `error: unexpected end-of-file`  flakiness

### ISSUE THREAD

**Issue by dpc** [DeterminateSystems/magic-nix-cache#32]
The CI in a project I started using `magic-nix-cache` is plagued
by a `error: unexpected end-of-file`Nix error flakiness. I need to restart a build good 2-3 times to get it to work.

https://github.com/rustshop/flakebox/actions/runs/6488634562/job/17621433941

I've never seen anything like that, and I've been using mostly cachix before, just running out of space for all my projects. There's nothing really pointing at `magic-nix-cache`'s fault in this, but [eventually occurred to me to try with disabled magic-nix-cache](https://github.com/rustshop/flakebox/pull/83) and voila, the problem is immediately gone (but so is the sweet caching benefits :D). [I kicked off another build on a seprate PR](https://github.com/rustshop/flakebox/actions/runs/6490214873/job/17625671386?pr=84), also seems to be passing the downloading cached artifacts stage just fine.

The `unexpected end-of-file` seems to be a de-serialization error in Nix. Possibly something got corrupted/truncated somewhere in the cache?

**Comment by dpc** [comment]
I have wiped the cache with

```
> cat wipecache.sh 
#!/usr/bin/env bash

GH_REPO=rustshop/flakebox

gh api --paginate -H "Accept: application/vnd.github+json" \
  "/repos/${GH_REPO}/actions/caches" \
  | for ID in `jq '.actions_caches[].id'`; \
    do echo "Deleting $ID"; \
       gh api --method DELETE "/repos/${GH_REPO}/actions/caches/$ID" | echo; done
```

and jobs passed, so I'm quite convinced that something bad was sitting in that cache. I will report back if it ever shows up again.

**Comment by dpc** [comment]
The problem is back.

**Comment by dpc** [comment]
For the record: happened again.

**Comment by solidsnakedev** [comment]
any feedback? , we've also experience the same issues multiple times
https://github.com/Anastasia-Labs/smart-handles/actions/runs/7194163348/job/19594100339

**Comment by henrytill** [comment]
Also got hit with a surge of these errors last night in a private repo, ultra-minimal workflow:

```yml
name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
```

Ran `nix flake update` after several re-runs didn't work, which allowed it to pass once, but subsequent commits resumed failing with `error: unexpected end-of-file`.  Ultimately had to disable `magic-nix-cache` to make progress.
